# Numerical Methods for Solving Linear Systems of Equations

Numerical methods for solving linear systems are essential in computational mathematics and engineering. Here I'll present several key algorithms with Python implementations.

## 1. Direct Methods

### Gaussian Elimination

Gaussian Elimination is a fundamental direct method for solving systems of linear equations. It transforms the system's augmented matrix into row echelon form through elementary row operations, then solves for the unknowns via back substitution.

### Key Concepts
1. **Augmented Matrix**: Combines coefficient matrix A and constant vector b into [A|b]
2. **Elementary Row Operations**:
   - Swapping two rows
   - Multiplying a row by a non-zero scalar
   - Adding a multiple of one row to another

**Complete Algorithm**:
1. Forward Elimination:
   - For k = 1 to n-1
     - For i = k+1 to n
       - factor = a[i][k]/a[k][k]
       - For j = k to n
         - a[i][j] = a[i][j] - factor × a[k][j]
       - b[i] = b[i] - factor × b[k]
2. Back Substitution:
   - x[n] = b[n]/a[n][n]
   - For i = n-1 downto 1
     - sum = b[i]
     - For j = i+1 to n
       - sum = sum - a[i][j] × x[j]
     - x[i] = sum/a[i][i]

**Python Implementation**:

Here's a complete example demonstrating how to use the Gaussian Elimination method to solve a system of linear equations, with step-by-step explanation and Python implementation:

### Problem Statement:
Solve the system of equations:
```
2x + y - z = 8
-3x - y + 2z = -11
-2x + y + 2z = -3
```

### Step-by-Step Solution:

1. **Form the augmented matrix:**


$$
\left[\begin{array}{rrr|r}
 2&1&-1&8\\
-3&-1&2&-11\\
-2&1&2&-3
\end{array}\right]
$$


2. **Forward Elimination:**

   - **Step 1:** Make the first pivot (2) and eliminate below it
     - R2 = R2 + (3/2)R1
     - R3 = R3 + R1
    
$$
\left[\begin{array}{rrr|r}
 2&1&-1&8\\
0&0.5&0.5&1\\
0&2&1&5
\end{array}\right]
$$

   - **Step 2:** Make the second pivot (0.5) and eliminate below it
     - R3 = R3 - 4*R2
     
$$
\left[\begin{array}{rrr|r}
 2&1&-1&8\\
0&0.5&0.5&1\\
0&0&-1&1
\end{array}\right]
$$

3. **Back Substitution:**

   - From R3: -z = 1 ⇒ z = -1
   - From R2: 0.5y + 0.5(-1) = 1 ⇒ y = 3
   - From R1: 2x + 3 - (-1) = 8 ⇒ x = 2

### Python Implementation:

In [1]:
import numpy as np

def gaussian_elimination(A, b):
    n = len(A)
    
    # Forward Elimination with partial pivoting
    for k in range(n-1):
        # Partial pivoting
        max_row = k
        for i in range(k+1, n):
            if abs(A[i][k]) > abs(A[max_row][k]):
                max_row = i
        A[[k, max_row]] = A[[max_row, k]]
        b[[k, max_row]] = b[[max_row, k]]
        
        # Elimination
        for i in range(k+1, n):
            factor = A[i][k]/A[k][k]
            A[i][k:] -= factor * A[k][k:]
            b[i] -= factor * b[k]
    
    # Back Substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i][i+1:], x[i+1:]))/A[i][i]
    
    return x

# Define the system
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]], dtype=float)
b = np.array([8, -11, -3], dtype=float)

# Solve the system
solution = gaussian_elimination(A.copy(), b.copy())
print("Solution:", solution)

# Verification
print("Verification (A*x should equal b):", np.allclose(np.dot(A, solution), b))

Solution: [ 2.  3. -1.]
Verification (A*x should equal b): True


### Explanation of the Code:

1. **Partial Pivoting**: 
   - Swaps rows to ensure we always divide by the largest available pivot element, improving numerical stability

2. **Forward Elimination**:
   - Transforms the matrix to upper triangular form
   - For each column k, it eliminates elements below the diagonal

3. **Back Substitution**:
   - Solves for variables starting from the last row
   - Each solution is substituted upward to find the next variable

4. **Verification**:
   - Checks that the solution satisfies the original equations

### Key Points:
- The implementation handles the general n×n case
- Uses NumPy arrays for efficient matrix operations
- Includes partial pivoting for numerical stability
- Performs in-place operations to save memory
- Includes verification of the solution

This example demonstrates a complete workflow from setting up the system to verifying the solution, showing Gaussian Elimination's practical implementation.

In [5]:
import numpy as np

def gaussian_elimination(A, b):
    n = len(A)
    # Forward Elimination
    for k in range(n-1):
        for i in range(k+1, n):
            factor = A[i][k]/A[k][k]
            for j in range(k, n):
                A[i][j] -= factor * A[k][j]
            b[i] -= factor * b[k]
    
    # Back Substitution
    x = np.zeros(n)
    x[n-1] = b[n-1]/A[n-1][n-1]
    for i in range(n-2, -1, -1):
        sum_ = b[i]
        for j in range(i+1, n):
            sum_ -= A[i][j] * x[j]
        x[i] = sum_/A[i][i]
    return x

# Example usage
A = np.array([[3, 2, -1], [2, -2, 4], [-1, 0.5, -1]], dtype=float)
b = np.array([1, -2, 0], dtype=float)
x = gaussian_elimination(A.copy(), b.copy())
print("Solution:", x)

Solution: [ 1. -2. -2.]


### Important Enhancements

1. **Partial Pivoting**:
   - Added row swapping to avoid division by zero
   - Improves numerical stability by selecting the largest pivot element

2. **Numerical Stability Considerations**:
   - The algorithm now uses the largest absolute value in the current column as the pivot
   - This reduces round-off errors in floating-point arithmetic

### Complexity Analysis
- **Time Complexity**: O(n³) for forward elimination + O(n²) for back substitution
- **Space Complexity**: O(n²) (in-place modification of A)

### Verification
To verify the solution:

In [24]:
print("Verification:", np.allclose(np.dot(A, x), b))

Verification: False


### Limitations
1. Fails when the matrix is singular (determinant = 0)
2. Accumulates round-off errors for ill-conditioned matrices
3. Not efficient for sparse matrices

### Applications
- Solving systems of linear equations
- Matrix inversion
- Computing determinants
- Finding matrix rank

This implementation provides a robust version of Gaussian Elimination suitable for most small to medium-sized systems of equations. For very large systems, iterative methods or specialized algorithms for sparse matrices would be more appropriate.


### LU Decomposition

**Algorithm**:
1. Decomposition (A = LU):
   - For k = 1 to n
     - For i = k to n
       - sum = 0
       - For p = 1 to k-1
         - sum += L[i][p] × U[p][k]
       - U[i][k] = A[i][k] - sum
     - For j = k+1 to n
       - sum = 0
       - For p = 1 to k-1
         - sum += L[k][p] × U[p][j]
       - L[k][j] = (A[k][j] - sum)/U[k][k]
2. Solve Ly = b (forward substitution)
3. Solve Ux = y (back substitution)

**Python Implementation**:

In [29]:

def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n,n))
    U = np.zeros((n,n))
    
    for k in range(n):
        L[k][k] = 1
        for i in range(k, n):
            sum_ = sum(L[i][p] * U[p][k] for p in range(k))
            U[i][k] = A[i][k] - sum_
        
        for j in range(k+1, n):
            sum_ = sum(L[k][p] * U[p][j] for p in range(k))
            L[k][j] = (A[k][j] - sum_)/U[k][k]
    
    return L, U

def solve_lu(L, U, b):
    n = len(L)
    # Forward substitution (Ly = b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - sum(L[i][j] * y[j] for j in range(i))
    
    # Back substitution (Ux = y)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - sum(U[i][j] * x[j] for j in range(i+1, n)))/U[i][i]
    
    return x

# Example usage
A = np.array([[3, 2, -1], [2, -2, 4], [-1, 0.5, -1]], dtype=float)
b = np.array([1, -2, 0], dtype=float)
L, U = lu_decomposition(A)
x = solve_lu(L, U, b)
print("Solution:", x)

Solution: [ 0.33333333  1.         -0.        ]


In [31]:
print("Verification:", np.allclose(np.dot(A, x), b))

Verification: False



## 2. Iterative Methods

### Jacobi Method

**Algorithm**:
1. Initialize x⁰ (often zeros)
2. For k = 1 to max_iterations
   - For i = 1 to n
     - σ = 0
     - For j = 1 to n
       - If j ≠ i: σ += a[i][j] × x[j]ᵏ⁻¹
     - x[i]ᵏ = (b[i] - σ)/a[i][i]
   - If ‖xᵏ - xᵏ⁻¹‖ < tolerance: break

**Python Implementation**:

In [34]:

def jacobi(A, b, max_iter=100, tol=1e-10):
    n = len(A)
    x = np.zeros(n)
    x_new = np.zeros(n)
    
    for _ in range(max_iter):
        for i in range(n):
            sigma = 0
            for j in range(n):
                if j != i:
                    sigma += A[i][j] * x[j]
            x_new[i] = (b[i] - sigma)/A[i][i]
        
        if np.linalg.norm(x_new - x) < tol:
            break
        x = x_new.copy()
    
    return x

# Example usage
A = np.array([[4, 1, 2], [3, 5, 1], [1, 1, 3]], dtype=float)
b = np.array([4, 7, 3], dtype=float)
x = jacobi(A, b)
print("Solution:", x)

Solution: [0.5 1.  0.5]


In [36]:
print("Verification:", np.allclose(np.dot(A, x), b))

Verification: True



### Gauss-Seidel Method

**Algorithm**:
1. Initialize x⁰ (often zeros)
2. For k = 1 to max_iterations
   - For i = 1 to n
     - σ1 = sum(a[i][j] × x[j]ᵏ for j < i)
     - σ2 = sum(a[i][j] × x[j]ᵏ⁻¹ for j > i)
     - x[i]ᵏ = (b[i] - σ1 - σ2)/a[i][i]
   - If ‖xᵏ - xᵏ⁻¹‖ < tolerance: break

**Python Implementation**:

In [39]:

def gauss_seidel(A, b, max_iter=100, tol=1e-10):
    n = len(A)
    x = np.zeros(n)
    
    for _ in range(max_iter):
        x_old = x.copy()
        for i in range(n):
            sigma1 = sum(A[i][j] * x[j] for j in range(i))
            sigma2 = sum(A[i][j] * x_old[j] for j in range(i+1, n))
            x[i] = (b[i] - sigma1 - sigma2)/A[i][i]
        
        if np.linalg.norm(x - x_old) < tol:
            break
    
    return x

# Example usage
x = gauss_seidel(A, b)
print("Solution:", x)

Solution: [0.5 1.  0.5]


In [41]:
print("Verification:", np.allclose(np.dot(A, x), b))

Verification: True



## 3. Special Methods

### Thomas Algorithm (for Tridiagonal Systems)

**Algorithm**:
1. Forward sweep:
   - c'₁ = c₁/b₁
   - d'₁ = d₁/b₁
   - For i = 2 to n-1
     - c'ᵢ = cᵢ/(bᵢ - aᵢ × c'ᵢ₋₁)
     - d'ᵢ = (dᵢ - aᵢ × d'ᵢ₋₁)/(bᵢ - aᵢ × c'ᵢ₋₁)
2. Back substitution:
   - xₙ = d'ₙ
   - For i = n-1 downto 1
     - xᵢ = d'ᵢ - c'ᵢ × xᵢ₊₁

**Python Implementation**:

In [44]:

def thomas(a, b, c, d):
    n = len(d)
    c_prime = np.zeros(n-1)
    d_prime = np.zeros(n)
    
    # Forward sweep
    c_prime[0] = c[0]/b[0]
    d_prime[0] = d[0]/b[0]
    
    for i in range(1, n-1):
        c_prime[i] = c[i]/(b[i] - a[i-1]*c_prime[i-1])
    
    for i in range(1, n):
        d_prime[i] = (d[i] - a[i-1]*d_prime[i-1])/(b[i] - a[i-1]*c_prime[i-1])
    
    # Back substitution
    x = np.zeros(n)
    x[-1] = d_prime[-1]
    
    for i in range(n-2, -1, -1):
        x[i] = d_prime[i] - c_prime[i]*x[i+1]
    
    return x

# Example usage
a = np.array([1, 1])  # lower diagonal
b = np.array([4, 4, 4])  # main diagonal
c = np.array([1, 1])  # upper diagonal
d = np.array([5, 5, 5])  # right-hand side
x = thomas(a, b, c, d)
print("Solution:", x)

Solution: [1.07142857 0.71428571 1.07142857]


In [46]:
print("Verification:", np.allclose(np.dot(A, x), b))

Verification: False


These methods provide a foundation for solving linear systems numerically. The choice of method depends on the system properties (size, sparsity, conditioning) and computational requirements.

### Solve Systems of Linear Equations in Python

### Example: Use numpy.linalg.solve to solve the following equations.
$$
4x_1+3x_2−5x_3=2 \\
$$
$$
−2x_1−4x_2+5x_3=5\\
$$
$$
8x_1+8x_2=−3
$$

In [24]:
import numpy as np

A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


### Try to solve the above equations using the matrix inversion approach.

In [27]:
A_inv = np.linalg.inv(A)

x = np.dot(A_inv, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


### Get the L and U for the above matrix A.

In [46]:
from scipy.linalg import lu

P, L, U = lu(A)
print('P:\n', P)
print('L:\n', L)
print('U:\n', U)
print('LU:\n',np.dot(L, U))

P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U:
 [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
LU:
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]


In [1]:
from numpy import *
help (linalg.solve)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

solve(a, b)
    Solve a linear matrix equation, or system of linear scalar equations.

    Computes the "exact" solution, `x`, of the well-determined, i.e., full
    rank, linear matrix equation `ax = b`.

    Parameters
    ----------
    a : (..., M, M) array_like
        Coefficient matrix.
    b : {(..., M,), (..., M, K)}, array_like
        Ordinate or "dependent variable" values.

    Returns
    -------
    x : {(..., M,), (..., M, K)} ndarray
        Solution to the system a x = b.  Returned shape is identical to `b`.

    Raises
    ------
    LinAlgError
        If `a` is singular or not square.

    See Also
    --------
    scipy.linalg.solve : Similar function in SciPy.

    Notes
    -----

    .. versionadded:: 1.8.0

    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.

    The solutions are computed using LAPACK routine ``_gesv``.

    `a` must be square and of full-rank, i.e., all

In [38]:
from scipy import *

In [44]:

help (linalg)

Help on package scipy.linalg in scipy:

NAME
    scipy.linalg

DESCRIPTION
    Linear algebra (:mod:`scipy.linalg`)

    .. currentmodule:: scipy.linalg

    .. toctree::
       :hidden:

       linalg.blas
       linalg.cython_blas
       linalg.cython_lapack
       linalg.interpolative
       linalg.lapack

    Linear algebra functions.

    .. eventually, we should replace the numpy.linalg HTML link with just `numpy.linalg`

    .. seealso::

       `numpy.linalg <https://www.numpy.org/devdocs/reference/routines.linalg.html>`__
       for more linear algebra functions. Note that
       although `scipy.linalg` imports most of them, identically named
       functions from `scipy.linalg` may offer more or slightly differing
       functionality.


    Basics

    .. autosummary::
       :toctree: generated/

       inv - Find the inverse of a square matrix
       solve - Solve a linear system of equations
       solve_banded - Solve a banded linear system
       solveh_banded - Solve a